### ISSUE TITLE
PyTechBrain_test - nie uruchamia się w Linux Mint19 Python3

### ISSUE THREAD

**Issue by abixadamj** [ABIX-Edukacja/PyTechBrain#3]
Urządzenie podpięte:

```
[134937.009885] usb 1-2: new full-speed USB device number 6 using xhci_hcd
[134937.165199] usb 1-2: New USB device found, idVendor=0403, idProduct=6015
[134937.165205] usb 1-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[134937.165209] usb 1-2: Product: FT231X USB UART
[134937.165213] usb 1-2: Manufacturer: FTDI
[134937.165217] usb 1-2: SerialNumber: DN02P9C7
[134937.215326] usbcore: registered new interface driver usbserial_generic
[134937.215360] usbserial: USB Serial support registered for generic
[134937.222325] usbcore: registered new interface driver ftdi_sio
[134937.222357] usbserial: USB Serial support registered for FTDI USB Serial Device
[134937.222552] ftdi_sio 1-2:1.0: FTDI USB Serial Device converter detected
[134937.222614] usb 1-2: Detected FT-X
[134937.223108] usb 1-2: FTDI USB Serial Device converter now attached to ttyUSB0

```

Próba uruchomienia:

```
adasiek@adasiek-desktop:~/PyTechBrain$ python3 PyTechBrain_test.py 
Traceback (most recent call last):
  File "/home/adasiek/.local/lib/python3.6/site-packages/serial/serialposix.py", line 265, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: 'NULL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PyTechBrain_test.py", line 24, in <module>
    board = Arduino(port)
  File "/usr/local/lib/python3.6/dist-packages/pyfirmata/__init__.py", line 16, in __init__
    super(Arduino, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pyfirmata/pyfirmata.py", line 89, in __init__
    self.sp = serial.Serial(port, baudrate, timeout=timeout)
  File "/home/adasiek/.local/lib/python3.6/site-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/home/adasiek/.local/lib/python3.6/site-packages/serial/serialposix.py", line 268, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port NULL: [Errno 2] No such file or directory: 'NULL'

System:
```
adasiek@adasiek-desktop: /PyTechBrain$ uname -a
Linux adasiek-desktop 4.15.0-38-generic #41-Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
adasiek@adasiek-desktop:/PyTechBrain$ python3 -V
Python 3.6.6

```

```

**Comment by abixadamj** [comment]
```
adasiek@adasiek-desktop:~/PyTechBrain$ python3 comport3.py 
Lista portów szeregowych
================================================================================
/dev/ttyUSB0 	 FT231X USB UART 	 USB VID:PID=0403:6015 SER=DN02P9C7 LOCATION=1-2
================================================================================
Naciśnij CTRL + C
^COK

```

**Comment by abixadamj** [comment]
ok, aktualna wersja działa poprawnie.
